void square(int size){
    Forward size in m;
    Right size in m;
    Clock 90;
    Forward size in m;
    Clock 90;
    Forward size in m;
    Clock 90;
}

int loopings = 10;
for(int i=0;i<loopings;i=i+1){
    Print i;
    ModifySpeed (i+1)*10 in m;
    square(5);
}
