/******************************************************************************
 * This file was generated by langium-cli 2.0.1.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import type { LangiumGeneratedServices, LangiumGeneratedSharedServices, LangiumSharedServices, LangiumServices, LanguageMetaData, Module } from 'langium';
import { RobotScriptAstReflection } from '../generated/ast.js';
import { RobotScriptGrammar } from './grammar.js';

export const RobotScriptLanguageMetaData = {
    languageId: 'robot-script',
    fileExtensions: ['.rbs'],
    caseInsensitive: false
} as const satisfies LanguageMetaData;

export const RobotScriptGeneratedSharedModule: Module<LangiumSharedServices, LangiumGeneratedSharedServices> = {
    AstReflection: () => new RobotScriptAstReflection()
};

export const RobotScriptGeneratedModule: Module<LangiumServices, LangiumGeneratedServices> = {
    Grammar: () => RobotScriptGrammar(),
    LanguageMetaData: () => RobotScriptLanguageMetaData,
    parser: {}
};
