void square(int size){
    Forward size in m;
    Right size*100 in cm;
    Clock 270;
    Backward size in m;
    Anticlock 180-90+90;
    Left (size*2)/2 in m;
    Clock 90;
}

// Draw five times the same square
// Each time faster

int loopings = 5;
for(int i=0;i<loopings;i=i+1){
    Print i;
    ModifySpeed (i+1)*10 in m;
    square(5);
}
