void square(int size){
    Forward 1 in m;
    Clock 90;
    Forward 10 in dm;
    Clock 90;
    Forward 100 in cm;
    Clock 90;
    Forward 1000 in mm;
    Clock 90;
}

// Follow a square path 3 times.

int square_number = 3;
double square_size = 2.5;

for(int i=0; i< square_number ; i = i+1){
    square(square_size);
}