// The default speed is 1 m/s. We set it to 2 m/s.
ModifySpeed 2 in m; 

// Draw a snail shell shape during 30 s.

int i=1;
while(CurrentTime in s < 30){
    Forward i in dm;
    Left i in dm;
    i = i +1;
}
