import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { RpcGeneratedModule, RpcGeneratedSharedModule } from './generated/module.js';
import { RpcValidator, registerValidationChecks } from './rpc-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RpcAddedServices = {
    validation: {
        RpcValidator: RpcValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RpcServices = LangiumServices & RpcAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RpcModule: Module<RpcServices, PartialLangiumServices & RpcAddedServices> = {
    validation: {
        RpcValidator: () => new RpcValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRpcServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Rpc: RpcServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RpcGeneratedSharedModule
    );
    const Rpc = inject(
        createDefaultModule({ shared }),
        RpcGeneratedModule,
        RpcModule
    );
    shared.ServiceRegistry.register(Rpc);
    registerValidationChecks(Rpc);
    return { shared, Rpc };
}
